//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public courseList()
        {
            this.Course_Allocation = new HashSet<Course_Allocation>();
            this.COURSE_INST_PREFERENCES = new HashSet<COURSE_INST_PREFERENCES>();
            this.COURSE_INST_PREFERENCES1 = new HashSet<COURSE_INST_PREFERENCES>();
            this.course_section_timing = new HashSet<course_section_timing>();
        }
    
        public string Course_id { get; set; }
        public string Course_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Allocation> Course_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_INST_PREFERENCES> COURSE_INST_PREFERENCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_INST_PREFERENCES> COURSE_INST_PREFERENCES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_section_timing> course_section_timing { get; set; }
    }
}
