//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Allocation
    {
        public string CourseID { get; set; }
        public string CourseName { get; set; }
        public string Section { get; set; }
        public Nullable<int> InstructorID { get; set; }
    
        public virtual COURSE_INST_PREFERENCES COURSE_INST_PREFERENCES { get; set; }
        public virtual courseList courseList { get; set; }
        public virtual section section1 { get; set; }
    }
}
