//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_INST_PREFERENCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSE_INST_PREFERENCES()
        {
            this.Course_Allocation = new HashSet<Course_Allocation>();
        }
    
        public int Instructor_id { get; set; }
        public string Instructor_name { get; set; }
        public string pref_course_id_1 { get; set; }
        public string pref_course_id_2 { get; set; }
        public Nullable<int> pref_timeslotID_1 { get; set; }
        public Nullable<int> pref_timeslotID_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Allocation> Course_Allocation { get; set; }
        public virtual courseList courseList { get; set; }
        public virtual courseList courseList1 { get; set; }
        public virtual course_timeslot course_timeslot { get; set; }
        public virtual course_timeslot course_timeslot1 { get; set; }
    }
}
