//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_Allocation
    {
        public string LabID { get; set; }
        public string LabName { get; set; }
        public string Section { get; set; }
        public Nullable<int> InstructorID { get; set; }
    
        public virtual LAB_INST_PREFERENCE LAB_INST_PREFERENCE { get; set; }
        public virtual labList labList { get; set; }
        public virtual section section1 { get; set; }
    }
}
