//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_timeslot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lab_timeslot()
        {
            this.LAB_INST_PREFERENCE = new HashSet<LAB_INST_PREFERENCE>();
            this.LAB_INST_PREFERENCE1 = new HashSet<LAB_INST_PREFERENCE>();
        }
    
        public int labTimeslot_id { get; set; }
        public string labTiming { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAB_INST_PREFERENCE> LAB_INST_PREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAB_INST_PREFERENCE> LAB_INST_PREFERENCE1 { get; set; }
    }
}
