//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_INST_PREFERENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LAB_INST_PREFERENCE()
        {
            this.Lab_Allocation = new HashSet<Lab_Allocation>();
        }
    
        public int Instructor_id { get; set; }
        public string Instructor_name { get; set; }
        public Nullable<decimal> gpa { get; set; }
        public string uni_name { get; set; }
        public string experience { get; set; }
        public string pref_lab_id_1 { get; set; }
        public string pref_lab_id_2 { get; set; }
        public Nullable<int> non_pref_timeslotID_1 { get; set; }
        public Nullable<int> non_pref_timeslotID_2 { get; set; }
        public string lab_id_1_grade { get; set; }
        public string lab_id_2_grade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab_Allocation> Lab_Allocation { get; set; }
        public virtual lab_timeslot lab_timeslot { get; set; }
        public virtual lab_timeslot lab_timeslot1 { get; set; }
        public virtual labList labList { get; set; }
        public virtual labList labList1 { get; set; }
    }
}
