//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class labs_section_timing
    {
        public string lab_id { get; set; }
        public string lab_name { get; set; }
        public string lab_section { get; set; }
        public string lab_timing { get; set; }
    
        public virtual labList labList { get; set; }
        public virtual section section { get; set; }
    }
}
