//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SE_TEAM2_dbEntities1 : DbContext
    {
        public SE_TEAM2_dbEntities1()
            : base("name=SE_TEAM2_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course_Allocation> Course_Allocation { get; set; }
        public virtual DbSet<COURSE_INST_PREFERENCES> COURSE_INST_PREFERENCES { get; set; }
        public virtual DbSet<course_section_timing> course_section_timing { get; set; }
        public virtual DbSet<course_timeslot> course_timeslot { get; set; }
        public virtual DbSet<courseList> courseLists { get; set; }
        public virtual DbSet<Lab_Allocation> Lab_Allocation { get; set; }
        public virtual DbSet<LAB_INST_PREFERENCE> LAB_INST_PREFERENCE { get; set; }
        public virtual DbSet<lab_timeslot> lab_timeslot { get; set; }
        public virtual DbSet<labList> labLists { get; set; }
        public virtual DbSet<labs_section_timing> labs_section_timing { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<venue> venues { get; set; }
        public virtual DbSet<timetable> timetables { get; set; }
    
        public virtual int check_course_clash(Nullable<int> instructor_id, string course_id, ObjectParameter clash)
        {
            var instructor_idParameter = instructor_id.HasValue ?
                new ObjectParameter("instructor_id", instructor_id) :
                new ObjectParameter("instructor_id", typeof(int));
    
            var course_idParameter = course_id != null ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("check_course_clash", instructor_idParameter, course_idParameter, clash);
        }
    
        public virtual int check_timing_clash(Nullable<int> instructor_id, string time_slot_id, ObjectParameter clash)
        {
            var instructor_idParameter = instructor_id.HasValue ?
                new ObjectParameter("instructor_id", instructor_id) :
                new ObjectParameter("instructor_id", typeof(int));
    
            var time_slot_idParameter = time_slot_id != null ?
                new ObjectParameter("time_slot_id", time_slot_id) :
                new ObjectParameter("time_slot_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("check_timing_clash", instructor_idParameter, time_slot_idParameter, clash);
        }
    
        public virtual int check_venue_clash(string venue_id, Nullable<System.TimeSpan> time_slot, ObjectParameter clash)
        {
            var venue_idParameter = venue_id != null ?
                new ObjectParameter("venue_id", venue_id) :
                new ObjectParameter("venue_id", typeof(string));
    
            var time_slotParameter = time_slot.HasValue ?
                new ObjectParameter("time_slot", time_slot) :
                new ObjectParameter("time_slot", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("check_venue_clash", venue_idParameter, time_slotParameter, clash);
        }
    }
}
