//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public string timetable_ver { get; set; }
        public string coursetimetable_slots { get; set; }
        public string labtimetable_slots { get; set; }
        public string timetable_venues { get; set; }
    
        public virtual venue venue { get; set; }
    }
}
